#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X


#if [[ $(xrandr -q | grep 'HDMI1 connected')]]; then
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1360x768 --rotate normal --right-of eDP1
#fi
bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX X


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Imágenes/Wallpapers/anm6655.jpg
~/.config/polybar/./launch.sh
picom -f &
bspc config border_width 0
setxkbmap -option caps:swapescape &
