#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected')]]; then
xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1360x768 --rotate normal --right-of eDP 
fi
bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

~/.config/polybar/./launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a colorpicker sticky=off state=floating rectangle=424x175+0+0 center=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/ramzzs/Imágenes/Wallpapers/elma-wallpaper-1.png

picom --experimental-backends &
bspc config border_width 0

xbacklight -set 30 &
xinput --disable 'Elan Touchpad' &
